### ISSUE TITLE
It is trying to download *.tar.gz file when npm rebuild

### ISSUE THREAD

**Issue by leochen1216** [ForbesLindesay/thread-sleep#10]
I notice that it tries to download *.tar.gz file from amazonaws.com when `npm rebuild`. The build server in my company can't connect to internet for security reasons. 

```
node-pre-gyp http GET https://node-pre-gyp-forbeslindesay.s3.amazonaws.com/thread_sleep/v1.0.4/Release/thread_sleep-v1.0.4-node-v11-linux-x64.tar.gz
node-pre-gyp http connect ETIMEDOUT (falling back to source compile with node-gyp) 
```

Is there a way to walkaround this issue?

**Comment by leochen1216** [comment]
Found the solution, I can download that file and add it to `lib/binding/Release/node-v11-linux-x64/thread_sleep.node` in my repo.

**Comment by TimothyGu** [comment]
… and it's time to update to Node.js 4 :)

We'll remove support for Node.js 0.10 next release.

**Comment by ForbesLindesay** [comment]
What's the plan once we drop support for 0.10?  We could just go full circle and build this on top of spawnSync :smile:

**Comment by TimothyGu** [comment]
> We could just go full circle and build this on top of spawnSync

Using the `sleep` unix command? That's not really portable…

**Comment by ForbesLindesay** [comment]
Using a node.js script that just contains:

``` js
setTimeout(function(){}, process.argv[2]);
```

**Comment by TimothyGu** [comment]
@ForbesLindesay done using `node -e` rather than a new file: https://github.com/ForbesLindesay/thread-sleep/compare/425b236...master#diff-168726dbe96b3ce427e7fedce31bb0bc.

I also needed to use some [hack](https://github.com/ForbesLindesay/thread-sleep/commit/9c0911d8a3bb443818edc03941147e0a1a7ecbb6) to work around the long latency of process spawning:

``` sh
$ node -pe "process.platform + ' ' + process.arch + ' ' + process.version"
linux x64 v4.1.2
$ time node -e 'setTimeout(function() {}, 0);'

real    0m0.121s
user    0m0.112s
sys     0m0.008s
```

``` sh
$ node -pe "process.platform + ' ' + process.arch + ' ' + process.version"
win32 x64 v4.1.2
$ time node -e 'setTimeout(function() {}, 0);'

real    0m0.195s
user    0m0.015s
sys     0m0.031s
```

Only thing I'm worried about is that now that npm's engineStrict property is deprecated, there is no way to enforce that only supported Node.js runtime is allowed.

**Comment by ForbesLindesay** [comment]
postinstall script that does:

``` js
if (!require('child_process').execFileSync) {
  console.error('thread-sleep@' + require('./package.json').version + ' requires node@4.0.0 or later');
  console.error('either update node or use an earlier version of thread-sleep');
  process.exit(1);
}
```

Another option though might be to leave this module doing the native implementation (since it's probably more accurate/less cpu intensive) and instead use this as a fallback within [try-thread-sleep](https://github.com/ForbesLindesay/try-thread-sleep) for when native compilation fails.

Incidentally, the only reason I wrote this module was for use in [spawn-sync](https://github.com/ForbesLindesay/spawn-sync) so personally I have no use case for it in a post 4.0.0 world.
